spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(L25WvmgFeXMISd0eGfmGprAZwPXfjudFOnGnX5C4JTSsRnJwkAqz4l44PiS9xz82lvRfBenSr2d2DXJgMEgZIg==)
    username: ENC(71M9V6VbtB6S0i/S/HcxPmy/TTiqAsrY)
    password: ENC(zJWvcj62mjMzbiFJEacMGw==)
    hikari:
      schema: ENC(C+zieUA6YJjngYOmMYzJvA==)

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  mail:
    host: smtp.gmail.com
    port: 587
    username: oceana5785@gmail.com
    password: gibcfckgbuyrtnyu
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

logging.level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

