spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/captain
    username: sa
    password:
    hikari:
#      schema: ticket

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  mail:
    host: smtp.gmail.com
    port: 587
    username: xe00123@gmail.com
    password: qjbsxmgegpwnyxdo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true

logging.level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #org.hibernate.type: trace

